title: ABIGAIL PLIMMER
description: PhD Researcher in Mantle Geodynamics
site_title: 'Abigail Plimmer'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: AbiPlimmer
email: plimmerar@cardiff.ac.uk

# absolute or relative
profile_picture: assets/images/pp.jpg
